### ISSUE TITLE
Only "simple webhook" is working

### ISSUE THREAD

**Issue by TAnas0** [hasura/sample-auth-webhook#3]
Hey,

I deployed this repository in Now trying to add authentication to my backend.
Only the endpoint `/simple/webhook` worked and I cannot use `GET` on the other two endpoints: `/auth0` and `/firebase`.

My main interest is auth0 and I  believe to have set the variable `AUTH_ZERO_DOMAIN` correctly.

Here is the link to the webhook: https://sample-auth-webhook-omfuteznfi.now.sh

Can you please help me pinpoint the source of the error?

I have also deployed the GraphQL engine and pointed it to the simple webhook endpoint by setting the environment variable: 
```bash
"HASURA_GRAPHQL_AUTH_HOOK": "https://sample-auth-webhook-omfuteznfi.now.sh/simple/webhook"
```
I still can not access data and get the following response that states : "Error: Invalid response from authorization hook"
![image](https://user-images.githubusercontent.com/12121506/44737170-26cef780-aae9-11e8-9cb9-6b8c011b66c1.png)

I really liked the GraphQL engine and am trying to explore it further and strongly considering it for production.
I would appreciate your help on this issue.

**Comment by TAnas0** [comment]
Sure enough, I suffer all day from the problem and only realize how stupid it is once I get away from the keyboard for a minute.

The `auth0` and `firebase` authentication endpoint are respectiveley `/auth0/webhook` and `/firebase/webhook`. And not `/auth0` and `/firebase`.

Hope that at least it will help someone on the future

**Comment by TAnas0** [comment]
I still face a problem though concerning the second part of my issue, where I still get the same response in the screenshot.

**Comment by wawhal** [comment]
Hey @TAnas0!

I see that you have deployed using `now`
I tried to replicate your issue, but it works fine for me.

Just to be sure, can you confirm that you ran the following command?

```
$ now -e AUTH_ZERO_DOMAIN='test.auth0.com'
```
